// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pmvihffnpgjrjwjesein.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtdmloZmZucGdqcmp3amVzZWluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NDgyMTIsImV4cCI6MjA3ODEyNDIxMn0.9TBAUab4cINF3--VU1Pcx3O8AhOaTUu-iE7cNuDN92s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);